name: Compare packages
on:
  pull_request:
    paths:
      - "package.json"

permissions:
  pull-requests: write
  contents: write

jobs:
  compare-packages:
    name: Compare changes to package.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout code - base branch
        uses: actions/checkout@v4
        with:
          path: base
          ref: ${{ github.event.pull_request.base.sha }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - name: Compare packages
        run: |
          node .github/scripts/compare-packages.js \
          --base=base/package.json \
          --compare=package.json \
          --output=$RUNNER_TEMP \
          --verbose
      - name: Read and assign to output
        if: hashFiles('${{ env.RUNNER_TEMP }}/report.md') != ''
        id: output
        run: |
          report='<!-- ypkmtr unique comment -->'
          while read line
          do
            report+=$line
          done < $RUNNER_TEMP/report.md
          echo "REPORT=$report" >> $GITHUB_OUTPUT
      - name: Comment on pull request
        if: steps.output.outputs.REPORT
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.output.outputs.REPORT }}
          check_for_duplicate_msg: false
          delete_prev_regex_msg: "<!-- ypkmtr unique comment -->"
      - name: Action summary
        if: steps.output.outputs.REPORT
        run: echo "${{ steps.output.outputs.REPORT }}" >> $GITHUB_STEP_SUMMARY
